<?php

use App\Framework\App;

use App\Framework\Middleware\AdminMiddleware;
use App\Framework\Middleware\CsrfMiddleware;
use GuzzleHttp\Psr7\ServerRequest;
use Laminas\HttpHandlerRunner\Emitter\SapiEmitter;
use Whoops\Handler\PrettyPageHandler;
use Whoops\Run;

require dirname(__DIR__).'/vendor/autoload.php';

if(session_status() === PHP_SESSION_NONE){
    session_start();
}

$whoops = new Run;
$whoops->pushHandler(new PrettyPageHandler);
$whoops->register();

$containerConfigPath= dirname(__DIR__).DIRECTORY_SEPARATOR.'config'.DIRECTORY_SEPARATOR.'container.php';



// Create the application instance
$app=(new App($containerConfigPath))
    // Add a middleware

    ->pipe(CsrfMiddleware::class)
    ->pipe(AdminMiddleware::class)
;

// Emit the HTTP response generated by the app, from the incoming request
(new SapiEmitter())->emit($app->handle(ServerRequest::fromGlobals()));
